
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.View;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author khalifardy
 */
public class KalkulatorFrame extends javax.swing.JFrame {

    /**
     * Creates new form KalkulatorFrame
     */
    private String usr;
    private String name;
    DefaultTableModel tabel_log;
    public KalkulatorFrame(String Username, String name) {
        initComponents();
        this.usr = Username;
        this.name = name;
        jLabel33.setText(Username);
        jLabel34.setText(name);
        String [] header = {"Dimensi", "Jenis Bangun", "Jenis hitungan","Hasil","Waktu"};
        tabel_log = new DefaultTableModel(header,0);
        Logtabel.setModel(tabel_log);
        show_tablelog();
        comboboxdimensi.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Bersihkan combo box kedua
                
                
                // Tambahkan item ke combo box kedua berdasarkan pilihan combo box pertama
                String selectedDimensi = (String) comboboxdimensi.getSelectedItem();
                jComboBoxgeometri.removeAllItems();
                if ("2D".equals(selectedDimensi)) {
                    jComboBoxgeometri.addItem("Persegi");
                    jComboBoxgeometri.addItem("Persegi Panjang");
                    jComboBoxgeometri.addItem("Segitiga");
                    jComboBoxgeometri.addItem("Lingkaran");
                } else if ("3D".equals(selectedDimensi)) {
                    jComboBoxgeometri.addItem("Balok");
                    jComboBoxgeometri.addItem("Kubus");
                    jComboBoxgeometri.addItem("Prisma");
                    jComboBoxgeometri.addItem("Tabung");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void show_tablelog() {
        int row = tabel_log.getRowCount();
    
    // Remove all rows from the table model
        for (int i = row - 1; i >= 0; i--) {
            tabel_log.removeRow(i);
        }
    
        try {
        // Buat kembali model tabel
        String[] header = {"Dimensi", "Jenis Bangun", "Jenis hitungan", "Hasil", "Waktu"};
        tabel_log = new DefaultTableModel(header, 0);
        Logtabel.setModel(tabel_log);

        Database db = new Database();
        String sql = "select * from log_hitung where user_id in (Select id from data_user where username = ?)";
        ResultSet rs = db.query_filter_login(sql, this.usr);

        while (rs.next()) {
            String data[] = {rs.getString("dimensi"), rs.getString("jenis_bangun"),
                    rs.getString("jenis_hitungan"), rs.getString("hasil"), rs.getString("waktu")};
            tabel_log.addRow(data);
        }
    } catch (SQLException ex) {
        Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        persegidialog = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sisispinner = new javax.swing.JSpinner();
        persegidisplay = new javax.swing.JTextField();
        kelilingpersegibutton = new javax.swing.JButton();
        luaspersegibutton = new javax.swing.JButton();
        segitigadialog = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        alassegitigaspinner = new javax.swing.JSpinner();
        sisi1segitigaspinner = new javax.swing.JSpinner();
        sisi2segitigaspinner = new javax.swing.JSpinner();
        tinggisegitigaspinner = new javax.swing.JSpinner();
        segitigadisplay = new javax.swing.JTextField();
        kelilingsegitigabutton = new javax.swing.JButton();
        luassegitigabutton = new javax.swing.JButton();
        persegipanjangdialog = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panjangpersegipanjangspinner = new javax.swing.JSpinner();
        lebarspinnerpersegipanjang = new javax.swing.JSpinner();
        displaypersegipanjang = new javax.swing.JTextField();
        kelilingpersegipanjangbutton = new javax.swing.JButton();
        luaspersegipanjang = new javax.swing.JButton();
        lingkarandialog = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jarijarilingkaranspinner = new javax.swing.JSpinner();
        jTextField1 = new javax.swing.JTextField();
        kelilinglingkaranbutton = new javax.swing.JButton();
        luaslingkaranbutton = new javax.swing.JButton();
        prismadialog = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        alasprismaspinner = new javax.swing.JSpinner();
        tinggisegitigaprismaspinner = new javax.swing.JSpinner();
        sisi1prismaspinner = new javax.swing.JSpinner();
        sisi2prismaspinner = new javax.swing.JSpinner();
        prismadisplay = new javax.swing.JTextField();
        luaspermukaanprismabutton = new javax.swing.JButton();
        volumeprismabutton = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        tinggiprismaspinner = new javax.swing.JSpinner();
        kubusdialog = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        rusukkubusspinner = new javax.swing.JSpinner();
        displaykubus = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        volumekubusbutton = new javax.swing.JButton();
        balokdialog = new javax.swing.JDialog();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        panjangbalokspinner = new javax.swing.JSpinner();
        lebarspinnerbalok = new javax.swing.JSpinner();
        tinggibalokspinner = new javax.swing.JSpinner();
        displaybalok = new javax.swing.JTextField();
        buttonluaspermukaanbalok = new javax.swing.JButton();
        volumebalokbutton = new javax.swing.JButton();
        tabungdialog = new javax.swing.JDialog();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jarijarispinnertabung = new javax.swing.JSpinner();
        tinggispinnertabung = new javax.swing.JSpinner();
        displaytabung = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        volumetabung = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboboxdimensi = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxgeometri = new javax.swing.JComboBox<>();
        pilihbutton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Logtabel = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        refreshbutton = new javax.swing.JButton();

        persegidialog.setMinimumSize(new java.awt.Dimension(500, 300));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setText("Persegi ");

        jLabel5.setText("panjang sisi");

        kelilingpersegibutton.setText("Keliling");
        kelilingpersegibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelilingpersegibuttonActionPerformed(evt);
            }
        });

        luaspersegibutton.setText("Luas");
        luaspersegibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luaspersegibuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout persegidialogLayout = new javax.swing.GroupLayout(persegidialog.getContentPane());
        persegidialog.getContentPane().setLayout(persegidialogLayout);
        persegidialogLayout.setHorizontalGroup(
            persegidialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, persegidialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(159, 159, 159))
            .addGroup(persegidialogLayout.createSequentialGroup()
                .addGroup(persegidialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(persegidialogLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel5)
                        .addGap(36, 36, 36)
                        .addComponent(sisispinner, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(persegidialogLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(persegidisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(persegidialogLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(kelilingpersegibutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(luaspersegibutton)
                .addGap(88, 88, 88))
        );
        persegidialogLayout.setVerticalGroup(
            persegidialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(persegidialogLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addGap(25, 25, 25)
                .addGroup(persegidialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sisispinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(persegidisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(persegidialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelilingpersegibutton)
                    .addComponent(luaspersegibutton))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        segitigadialog.setMinimumSize(new java.awt.Dimension(500, 500));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setText("Segitiga ");

        jLabel7.setText("alas");

        jLabel9.setText("sisi1");

        jLabel10.setText("sisi2");

        jLabel11.setText("tinggi");

        kelilingsegitigabutton.setText("Keliling");
        kelilingsegitigabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelilingsegitigabuttonActionPerformed(evt);
            }
        });

        luassegitigabutton.setText("Luas");
        luassegitigabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luassegitigabuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout segitigadialogLayout = new javax.swing.GroupLayout(segitigadialog.getContentPane());
        segitigadialog.getContentPane().setLayout(segitigadialogLayout);
        segitigadialogLayout.setHorizontalGroup(
            segitigadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, segitigadialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(152, 152, 152))
            .addGroup(segitigadialogLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(segitigadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(segitigadialogLayout.createSequentialGroup()
                        .addGroup(segitigadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(38, 38, 38)
                        .addGroup(segitigadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(alassegitigaspinner, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(sisi1segitigaspinner)
                            .addComponent(sisi2segitigaspinner)
                            .addComponent(tinggisegitigaspinner)))
                    .addGroup(segitigadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, segitigadialogLayout.createSequentialGroup()
                            .addComponent(kelilingsegitigabutton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(luassegitigabutton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(segitigadisplay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        segitigadialogLayout.setVerticalGroup(
            segitigadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(segitigadialogLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(segitigadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(alassegitigaspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(segitigadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(sisi1segitigaspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(segitigadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(sisi2segitigaspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(segitigadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(tinggisegitigaspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(segitigadisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(segitigadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelilingsegitigabutton)
                    .addComponent(luassegitigabutton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        persegipanjangdialog.setMinimumSize(new java.awt.Dimension(500, 400));

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel12.setText("PERSEGI PANJANG");

        jLabel13.setText("Panjang");

        jLabel14.setText("Lebar");

        kelilingpersegipanjangbutton.setText("Keliling");
        kelilingpersegipanjangbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelilingpersegipanjangbuttonActionPerformed(evt);
            }
        });

        luaspersegipanjang.setText("Luas");
        luaspersegipanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luaspersegipanjangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout persegipanjangdialogLayout = new javax.swing.GroupLayout(persegipanjangdialog.getContentPane());
        persegipanjangdialog.getContentPane().setLayout(persegipanjangdialogLayout);
        persegipanjangdialogLayout.setHorizontalGroup(
            persegipanjangdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(persegipanjangdialogLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(persegipanjangdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(persegipanjangdialogLayout.createSequentialGroup()
                        .addComponent(displaypersegipanjang, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addGroup(persegipanjangdialogLayout.createSequentialGroup()
                        .addGroup(persegipanjangdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(persegipanjangdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panjangpersegipanjangspinner)
                            .addComponent(lebarspinnerpersegipanjang))
                        .addGap(105, 105, 105))
                    .addGroup(persegipanjangdialogLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(kelilingpersegipanjangbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(luaspersegipanjang)
                        .addGap(72, 72, 72))))
        );
        persegipanjangdialogLayout.setVerticalGroup(
            persegipanjangdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(persegipanjangdialogLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(persegipanjangdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(panjangpersegipanjangspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(persegipanjangdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(lebarspinnerpersegipanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(displaypersegipanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(persegipanjangdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelilingpersegipanjangbutton)
                    .addComponent(luaspersegipanjang))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        lingkarandialog.setMinimumSize(new java.awt.Dimension(500, 300));

        jLabel15.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel15.setText("Lingkaran");

        jLabel16.setText("Jari-jari");

        kelilinglingkaranbutton.setText("Keliling");
        kelilinglingkaranbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelilinglingkaranbuttonActionPerformed(evt);
            }
        });

        luaslingkaranbutton.setText("Luas");
        luaslingkaranbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luaslingkaranbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lingkarandialogLayout = new javax.swing.GroupLayout(lingkarandialog.getContentPane());
        lingkarandialog.getContentPane().setLayout(lingkarandialogLayout);
        lingkarandialogLayout.setHorizontalGroup(
            lingkarandialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lingkarandialogLayout.createSequentialGroup()
                .addGroup(lingkarandialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(lingkarandialogLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(lingkarandialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jarijarilingkaranspinner, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(lingkarandialogLayout.createSequentialGroup()
                        .addContainerGap(70, Short.MAX_VALUE)
                        .addGroup(lingkarandialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(lingkarandialogLayout.createSequentialGroup()
                                .addComponent(kelilinglingkaranbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(luaslingkaranbutton))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(70, 70, 70))
        );
        lingkarandialogLayout.setVerticalGroup(
            lingkarandialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lingkarandialogLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(lingkarandialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jarijarilingkaranspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(lingkarandialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelilinglingkaranbutton)
                    .addComponent(luaslingkaranbutton))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        prismadialog.setMinimumSize(new java.awt.Dimension(500, 500));

        jLabel17.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel17.setText("PRISMA");

        jLabel18.setText("alas");

        jLabel19.setText("tinggi");

        jLabel20.setText("sisi1");

        jLabel21.setText("sisi2");

        luaspermukaanprismabutton.setText("luas permukaan");
        luaspermukaanprismabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luaspermukaanprismabuttonActionPerformed(evt);
            }
        });

        volumeprismabutton.setText("volume");
        volumeprismabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeprismabuttonActionPerformed(evt);
            }
        });

        jLabel35.setText("tinggi prisma");

        javax.swing.GroupLayout prismadialogLayout = new javax.swing.GroupLayout(prismadialog.getContentPane());
        prismadialog.getContentPane().setLayout(prismadialogLayout);
        prismadialogLayout.setHorizontalGroup(
            prismadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prismadialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(153, 153, 153))
            .addGroup(prismadialogLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(prismadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prismadialogLayout.createSequentialGroup()
                        .addGroup(prismadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prismadisplay, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(prismadialogLayout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addGap(18, 18, 18)
                                .addComponent(tinggiprismaspinner))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, prismadialogLayout.createSequentialGroup()
                                .addGroup(prismadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addGroup(prismadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tinggisegitigaprismaspinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alasprismaspinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sisi1prismaspinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sisi2prismaspinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(74, 74, 74))
                    .addGroup(prismadialogLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(luaspermukaanprismabutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volumeprismabutton)
                        .addGap(50, 50, 50))))
        );
        prismadialogLayout.setVerticalGroup(
            prismadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prismadialogLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(prismadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(alasprismaspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(prismadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tinggisegitigaprismaspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(prismadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(sisi1prismaspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(prismadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(sisi2prismaspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(prismadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(tinggiprismaspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(prismadisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(prismadialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luaspermukaanprismabutton)
                    .addComponent(volumeprismabutton))
                .addGap(46, 46, 46))
        );

        kubusdialog.setMinimumSize(new java.awt.Dimension(500, 300));

        jLabel22.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel22.setText("KUBUS");

        jLabel23.setText("rusuk");

        jButton1.setText("luas permukaan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        volumekubusbutton.setText("Volume");
        volumekubusbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumekubusbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kubusdialogLayout = new javax.swing.GroupLayout(kubusdialog.getContentPane());
        kubusdialog.getContentPane().setLayout(kubusdialogLayout);
        kubusdialogLayout.setHorizontalGroup(
            kubusdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kubusdialogLayout.createSequentialGroup()
                .addGroup(kubusdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(kubusdialogLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volumekubusbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(kubusdialogLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel22))
                    .addGroup(kubusdialogLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(kubusdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displaykubus, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kubusdialogLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(41, 41, 41)
                                .addComponent(rusukkubusspinner, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        kubusdialogLayout.setVerticalGroup(
            kubusdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kubusdialogLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(kubusdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(rusukkubusspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(displaykubus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kubusdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(volumekubusbutton))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        balokdialog.setMinimumSize(new java.awt.Dimension(500, 400));

        jLabel24.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel24.setText("BALOK");

        jLabel25.setText("panjang");

        jLabel26.setText("lebar");

        jLabel27.setText("Tinggi");

        buttonluaspermukaanbalok.setText("luas permukaan");
        buttonluaspermukaanbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonluaspermukaanbalokActionPerformed(evt);
            }
        });

        volumebalokbutton.setText("volume");
        volumebalokbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumebalokbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout balokdialogLayout = new javax.swing.GroupLayout(balokdialog.getContentPane());
        balokdialog.getContentPane().setLayout(balokdialogLayout);
        balokdialogLayout.setHorizontalGroup(
            balokdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balokdialogLayout.createSequentialGroup()
                .addGroup(balokdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(balokdialogLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel24))
                    .addGroup(balokdialogLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(balokdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(balokdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panjangbalokspinner, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(lebarspinnerbalok)
                            .addComponent(tinggibalokspinner)))
                    .addGroup(balokdialogLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(displaybalok, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(balokdialogLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(buttonluaspermukaanbalok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volumebalokbutton)
                .addGap(56, 56, 56))
        );
        balokdialogLayout.setVerticalGroup(
            balokdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balokdialogLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(balokdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(balokdialogLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addGroup(balokdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(panjangbalokspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26))
                    .addComponent(lebarspinnerbalok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(balokdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tinggibalokspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(displaybalok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(balokdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonluaspermukaanbalok)
                    .addComponent(volumebalokbutton))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tabungdialog.setMinimumSize(new java.awt.Dimension(500, 400));

        jLabel28.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel28.setText("TABUNG");

        jLabel29.setText("jari jari");

        jLabel30.setText("tinggi");

        jButton2.setText("luas permukaan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        volumetabung.setText("volume");
        volumetabung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumetabungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabungdialogLayout = new javax.swing.GroupLayout(tabungdialog.getContentPane());
        tabungdialog.getContentPane().setLayout(tabungdialogLayout);
        tabungdialogLayout.setHorizontalGroup(
            tabungdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabungdialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(151, 151, 151))
            .addGroup(tabungdialogLayout.createSequentialGroup()
                .addGroup(tabungdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabungdialogLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(tabungdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(displaytabung)
                            .addGroup(tabungdialogLayout.createSequentialGroup()
                                .addGroup(tabungdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30))
                                .addGap(41, 41, 41)
                                .addGroup(tabungdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jarijarispinnertabung, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(tinggispinnertabung)))))
                    .addGroup(tabungdialogLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton2)
                        .addGap(64, 64, 64)
                        .addComponent(volumetabung)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        tabungdialogLayout.setVerticalGroup(
            tabungdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabungdialogLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addGroup(tabungdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jarijarispinnertabung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(tabungdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(tinggispinnertabung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(displaytabung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabungdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(volumetabung))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel31.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel31.setText("KALKULATOR GEOMETRI");

        jLabel1.setText("dimensi");

        comboboxdimensi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2D", "3D" }));
        comboboxdimensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxdimensiActionPerformed(evt);
            }
        });

        jLabel2.setText("Geometri");

        jComboBoxgeometri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persegi", "Persegi Panjang", "Segitiga", "Lingkaran" }));
        jComboBoxgeometri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxgeometriActionPerformed(evt);
            }
        });

        pilihbutton.setText("Pilih");
        pilihbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxgeometri, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboboxdimensi, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(478, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(pilihbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboboxdimensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxgeometri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(pilihbutton)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kalkulator", jPanel1);

        Logtabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "dimensi", "Jenis Bangun", "Jenis Hitungan", "Hasil", "Waktu"
            }
        ));
        jScrollPane1.setViewportView(Logtabel);

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel3.setText("username :");

        jLabel32.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel32.setText("full name :");

        jLabel33.setText("jLabel33");

        jLabel34.setText("jLabel34");

        refreshbutton.setText("Refresh");
        refreshbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(74, 74, 74))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(79, 79, 79)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel33)))
                    .addComponent(refreshbutton))
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshbutton)
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("log", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void luaspersegibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luaspersegibuttonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int sisi = (Integer)sisispinner.getValue();
            Persegi tb = new Persegi("none","none",sisi);
            double hasil = tb.luas();
            persegidisplay.setText(String.valueOf(hasil));
            Database db = new Database();
            String selectedDimensi = (String) comboboxdimensi.getSelectedItem();
            String selectedDimensi2 = (String) jComboBoxgeometri.getSelectedItem();
            String jenis_hitungan = "Luas";
            LocalDateTime now = LocalDateTime.now();
            String sql = "insert into log_hitung (dimensi, jenis_bangun, jenis_hitungan, hasil, waktu, user_id) values (?, ?, ?, ?, ?, ?)";
            String sql2 = "Select * from data_user where username = ?";
            ResultSet rs = db.query_filter_login(sql2, this.usr);
            if(rs.next()){
                db.query_insert(sql, selectedDimensi, selectedDimensi2, jenis_hitungan, hasil, now,rs.getInt("id"));            
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(KalkulatorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_luaspersegibuttonActionPerformed

    private void pilihbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihbuttonActionPerformed
        // TODO add your handling code here:
        String selectedDimensi2 = (String) jComboBoxgeometri.getSelectedItem();
         if ("Persegi".equals(selectedDimensi2)) {
            persegidialog.setVisible(true);
                    jComboBoxgeometri.addItem("Persegi");
                    jComboBoxgeometri.addItem("Persegi Panjang");
                    jComboBoxgeometri.addItem("Segitiga");
                    jComboBoxgeometri.addItem("Lingkaran");
        }else if ("Persegi Panjang".equals(selectedDimensi2)){
            persegipanjangdialog.setVisible(true);
        }else if ("Segitiga".equals(selectedDimensi2)){
            segitigadialog.setVisible(true);
        }else if ("Lingkaran".equals(selectedDimensi2)){
            lingkarandialog.setVisible(true);
        }else if ("Balok".equals(selectedDimensi2)){
            balokdialog.setVisible(true);
        }else if ("Kubus".equals(selectedDimensi2)){
            kubusdialog.setVisible(true);
        }else if ("Prisma".equals(selectedDimensi2)){
            prismadialog.setVisible(true);
        }else if ("Tabung".equals(selectedDimensi2)){
            tabungdialog.setVisible(true);
        }
        
    }//GEN-LAST:event_pilihbuttonActionPerformed

    private void comboboxdimensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxdimensiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxdimensiActionPerformed

    private void jComboBoxgeometriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxgeometriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxgeometriActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            int jari_jari = (Integer)jarijarispinnertabung.getValue();
            int tinggi = (Integer)tinggispinnertabung.getValue();
            Tabung tb = new Tabung("none","none",jari_jari,tinggi);
            double hasil = tb.luaspermukaan();
            displaytabung.setText(String.valueOf(hasil));
            Database db = new Database();
            String selectedDimensi = (String) comboboxdimensi.getSelectedItem();
            String selectedDimensi2 = (String) jComboBoxgeometri.getSelectedItem();
            String jenis_hitungan = "Luas Permukaan";
            LocalDateTime now = LocalDateTime.now();
            String sql = "insert into log_hitung (dimensi, jenis_bangun, jenis_hitungan, hasil, waktu, user_id) values (?, ?, ?, ?, ?, ?)";
            String sql2 = "Select * from data_user where username = ?";
            ResultSet rs = db.query_filter_login(sql2, this.usr);
            if(rs.next()){
                db.query_insert(sql, selectedDimensi, selectedDimensi2, jenis_hitungan, hasil, now,rs.getInt("id"));            
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(KalkulatorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void volumetabungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumetabungActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int jari_jari = (Integer)jarijarispinnertabung.getValue();
            int tinggi = (Integer)tinggispinnertabung.getValue();
            Tabung tb = new Tabung("none","none",jari_jari,tinggi);
            double hasil = tb.volume();
            displaytabung.setText(String.valueOf(hasil));
            Database db = new Database();
            String selectedDimensi = (String) comboboxdimensi.getSelectedItem();
            String selectedDimensi2 = (String) jComboBoxgeometri.getSelectedItem();
            String jenis_hitungan = "Volume";
            LocalDateTime now = LocalDateTime.now();
            String sql = "insert into log_hitung (dimensi, jenis_bangun, jenis_hitungan, hasil, waktu, user_id) values (?, ?, ?, ?, ?, ?)";
            String sql2 = "Select * from data_user where username = ?";
            ResultSet rs = db.query_filter_login(sql2, this.usr);
            if(rs.next()){
                db.query_insert(sql, selectedDimensi, selectedDimensi2, jenis_hitungan, hasil, now,rs.getInt("id"));            
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(KalkulatorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_volumetabungActionPerformed

    private void refreshbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbuttonActionPerformed
        // TODO add your handling code here:
        show_tablelog();
    }//GEN-LAST:event_refreshbuttonActionPerformed

    private void buttonluaspermukaanbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonluaspermukaanbalokActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int panjang = (Integer)panjangbalokspinner.getValue();
            int lebar = (Integer)lebarspinnerbalok.getValue();
            int tinggi = (Integer)tinggibalokspinner.getValue();
            Balok tb = new Balok("none","none",panjang,lebar,tinggi);
            double hasil = tb.luaspermukaan();
            displaybalok.setText(String.valueOf(hasil));
            Database db = new Database();
            String selectedDimensi = (String) comboboxdimensi.getSelectedItem();
            String selectedDimensi2 = (String) jComboBoxgeometri.getSelectedItem();
            String jenis_hitungan = "Luas Permukaan";
            LocalDateTime now = LocalDateTime.now();
            String sql = "insert into log_hitung (dimensi, jenis_bangun, jenis_hitungan, hasil, waktu, user_id) values (?, ?, ?, ?, ?, ?)";
            String sql2 = "Select * from data_user where username = ?";
            ResultSet rs = db.query_filter_login(sql2, this.usr);
            if(rs.next()){
                db.query_insert(sql, selectedDimensi, selectedDimensi2, jenis_hitungan, hasil, now,rs.getInt("id"));            
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(KalkulatorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonluaspermukaanbalokActionPerformed

    private void volumebalokbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumebalokbuttonActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            int panjang = (Integer)panjangbalokspinner.getValue();
            int lebar = (Integer)lebarspinnerbalok.getValue();
            int tinggi = (Integer)tinggibalokspinner.getValue();
            Balok tb = new Balok("none","none",panjang,lebar,tinggi);
            double hasil = tb.volume();
            displaybalok.setText(String.valueOf(hasil));
            Database db = new Database();
            String selectedDimensi = (String) comboboxdimensi.getSelectedItem();
            String selectedDimensi2 = (String) jComboBoxgeometri.getSelectedItem();
            String jenis_hitungan = "Volume";
            LocalDateTime now = LocalDateTime.now();
            String sql = "insert into log_hitung (dimensi, jenis_bangun, jenis_hitungan, hasil, waktu, user_id) values (?, ?, ?, ?, ?, ?)";
            String sql2 = "Select * from data_user where username = ?";
            ResultSet rs = db.query_filter_login(sql2, this.usr);
            if(rs.next()){
                db.query_insert(sql, selectedDimensi, selectedDimensi2, jenis_hitungan, hasil, now,rs.getInt("id"));            
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(KalkulatorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_volumebalokbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            int sisi = (Integer)rusukkubusspinner.getValue();
            Kubus tb = new Kubus("none","none",sisi);
            double hasil = tb.luaspermukaan();
            displaykubus.setText(String.valueOf(hasil));
            Database db = new Database();
            String selectedDimensi = (String) comboboxdimensi.getSelectedItem();
            String selectedDimensi2 = (String) jComboBoxgeometri.getSelectedItem();
            String jenis_hitungan = "Luas Permukaan";
            LocalDateTime now = LocalDateTime.now();
            String sql = "insert into log_hitung (dimensi, jenis_bangun, jenis_hitungan, hasil, waktu, user_id) values (?, ?, ?, ?, ?, ?)";
            String sql2 = "Select * from data_user where username = ?";
            ResultSet rs = db.query_filter_login(sql2, this.usr);
            if(rs.next()){
                db.query_insert(sql, selectedDimensi, selectedDimensi2, jenis_hitungan, hasil, now,rs.getInt("id"));            
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(KalkulatorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void volumekubusbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumekubusbuttonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int sisi = (Integer)rusukkubusspinner.getValue();
            Kubus tb = new Kubus("none","none",sisi);
            double hasil = tb.volume();
            displaykubus.setText(String.valueOf(hasil));
            Database db = new Database();
            String selectedDimensi = (String) comboboxdimensi.getSelectedItem();
            String selectedDimensi2 = (String) jComboBoxgeometri.getSelectedItem();
            String jenis_hitungan = "Volume";
            LocalDateTime now = LocalDateTime.now();
            String sql = "insert into log_hitung (dimensi, jenis_bangun, jenis_hitungan, hasil, waktu, user_id) values (?, ?, ?, ?, ?, ?)";
            String sql2 = "Select * from data_user where username = ?";
            ResultSet rs = db.query_filter_login(sql2, this.usr);
            if(rs.next()){
                db.query_insert(sql, selectedDimensi, selectedDimensi2, jenis_hitungan, hasil, now,rs.getInt("id"));            
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(KalkulatorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_volumekubusbuttonActionPerformed

    private void luaspermukaanprismabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luaspermukaanprismabuttonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int alas = (Integer)alasprismaspinner.getValue();
            int tinggi = (Integer)tinggisegitigaprismaspinner.getValue();
            int sisi1 = (Integer)sisi1prismaspinner.getValue();
            int sisi2 = (Integer)sisi2prismaspinner.getValue();
            int tinggi_prisma = (Integer)tinggiprismaspinner.getValue();
            
            Prisma tb = new Prisma("none","none",alas,tinggi,sisi1,sisi2,tinggi_prisma);
            double hasil = tb.luaspermukaan();
            prismadisplay.setText(String.valueOf(hasil));
            Database db = new Database();
            String selectedDimensi = (String) comboboxdimensi.getSelectedItem();
            String selectedDimensi2 = (String) jComboBoxgeometri.getSelectedItem();
            String jenis_hitungan = "Luas Permukaan";
            LocalDateTime now = LocalDateTime.now();
            String sql = "insert into log_hitung (dimensi, jenis_bangun, jenis_hitungan, hasil, waktu, user_id) values (?, ?, ?, ?, ?, ?)";
            String sql2 = "Select * from data_user where username = ?";
            ResultSet rs = db.query_filter_login(sql2, this.usr);
            if(rs.next()){
                db.query_insert(sql, selectedDimensi, selectedDimensi2, jenis_hitungan, hasil, now,rs.getInt("id"));            
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(KalkulatorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_luaspermukaanprismabuttonActionPerformed

    private void volumeprismabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeprismabuttonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int alas = (Integer)alasprismaspinner.getValue();
            int tinggi = (Integer)tinggisegitigaprismaspinner.getValue();
            int sisi1 = (Integer)sisi1prismaspinner.getValue();
            int sisi2 = (Integer)sisi2prismaspinner.getValue();
            int tinggi_prisma = (Integer)tinggiprismaspinner.getValue();
            
            Prisma tb = new Prisma("none","none",alas,tinggi,sisi1,sisi2,tinggi_prisma);
            double hasil = tb.volume();
            prismadisplay.setText(String.valueOf(hasil));
            Database db = new Database();
            String selectedDimensi = (String) comboboxdimensi.getSelectedItem();
            String selectedDimensi2 = (String) jComboBoxgeometri.getSelectedItem();
            String jenis_hitungan = "Volume";
            LocalDateTime now = LocalDateTime.now();
            String sql = "insert into log_hitung (dimensi, jenis_bangun, jenis_hitungan, hasil, waktu, user_id) values (?, ?, ?, ?, ?, ?)";
            String sql2 = "Select * from data_user where username = ?";
            ResultSet rs = db.query_filter_login(sql2, this.usr);
            if(rs.next()){
                db.query_insert(sql, selectedDimensi, selectedDimensi2, jenis_hitungan, hasil, now,rs.getInt("id"));            
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(KalkulatorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_volumeprismabuttonActionPerformed

    private void kelilingpersegibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelilingpersegibuttonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int sisi = (Integer)sisispinner.getValue();
            Persegi tb = new Persegi("none","none",sisi);
            double hasil = tb.keliling();
            persegidisplay.setText(String.valueOf(hasil));
            Database db = new Database();
            String selectedDimensi = (String) comboboxdimensi.getSelectedItem();
            String selectedDimensi2 = (String) jComboBoxgeometri.getSelectedItem();
            String jenis_hitungan = "Keliling";
            LocalDateTime now = LocalDateTime.now();
            String sql = "insert into log_hitung (dimensi, jenis_bangun, jenis_hitungan, hasil, waktu, user_id) values (?, ?, ?, ?, ?, ?)";
            String sql2 = "Select * from data_user where username = ?";
            ResultSet rs = db.query_filter_login(sql2, this.usr);
            if(rs.next()){
                db.query_insert(sql, selectedDimensi, selectedDimensi2, jenis_hitungan, hasil, now,rs.getInt("id"));            
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(KalkulatorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kelilingpersegibuttonActionPerformed

    private void kelilingsegitigabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelilingsegitigabuttonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int alas = (Integer)alassegitigaspinner.getValue();
            int tinggi = (Integer)tinggisegitigaspinner.getValue();
            int sisi1 = (Integer)sisi1segitigaspinner.getValue();
            int sisi2 = (Integer)sisi2segitigaspinner.getValue();
            
            
            Segitiga tb = new Segitiga("none","none",alas,tinggi,sisi1,sisi2);
            double hasil = tb.keliling();
            segitigadisplay.setText(String.valueOf(hasil));
            Database db = new Database();
            String selectedDimensi = (String) comboboxdimensi.getSelectedItem();
            String selectedDimensi2 = (String) jComboBoxgeometri.getSelectedItem();
            String jenis_hitungan = "Keliling";
            LocalDateTime now = LocalDateTime.now();
            String sql = "insert into log_hitung (dimensi, jenis_bangun, jenis_hitungan, hasil, waktu, user_id) values (?, ?, ?, ?, ?, ?)";
            String sql2 = "Select * from data_user where username = ?";
            ResultSet rs = db.query_filter_login(sql2, this.usr);
            if(rs.next()){
                db.query_insert(sql, selectedDimensi, selectedDimensi2, jenis_hitungan, hasil, now,rs.getInt("id"));            
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(KalkulatorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kelilingsegitigabuttonActionPerformed

    private void luassegitigabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luassegitigabuttonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int alas = (Integer)alassegitigaspinner.getValue();
            int tinggi = (Integer)tinggisegitigaspinner.getValue();
            int sisi1 = (Integer)sisi1segitigaspinner.getValue();
            int sisi2 = (Integer)sisi2segitigaspinner.getValue();
            
            
            Segitiga tb = new Segitiga("none","none",alas,tinggi,sisi1,sisi2);
            double hasil = tb.luas();
            segitigadisplay.setText(String.valueOf(hasil));
            Database db = new Database();
            String selectedDimensi = (String) comboboxdimensi.getSelectedItem();
            String selectedDimensi2 = (String) jComboBoxgeometri.getSelectedItem();
            String jenis_hitungan = "Luas";
            LocalDateTime now = LocalDateTime.now();
            String sql = "insert into log_hitung (dimensi, jenis_bangun, jenis_hitungan, hasil, waktu, user_id) values (?, ?, ?, ?, ?, ?)";
            String sql2 = "Select * from data_user where username = ?";
            ResultSet rs = db.query_filter_login(sql2, this.usr);
            if(rs.next()){
                db.query_insert(sql, selectedDimensi, selectedDimensi2, jenis_hitungan, hasil, now,rs.getInt("id"));            
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(KalkulatorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_luassegitigabuttonActionPerformed

    private void kelilingpersegipanjangbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelilingpersegipanjangbuttonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int panjang = (Integer)panjangpersegipanjangspinner.getValue();
            int lebar = (Integer)lebarspinnerpersegipanjang.getValue();
            
            PersegiPanjang tb = new PersegiPanjang("none","none",panjang,lebar);
            double hasil = tb.keliling();
            displaypersegipanjang.setText(String.valueOf(hasil));
            Database db = new Database();
            String selectedDimensi = (String) comboboxdimensi.getSelectedItem();
            String selectedDimensi2 = (String) jComboBoxgeometri.getSelectedItem();
            String jenis_hitungan = "Keliling";
            LocalDateTime now = LocalDateTime.now();
            String sql = "insert into log_hitung (dimensi, jenis_bangun, jenis_hitungan, hasil, waktu, user_id) values (?, ?, ?, ?, ?, ?)";
            String sql2 = "Select * from data_user where username = ?";
            ResultSet rs = db.query_filter_login(sql2, this.usr);
            if(rs.next()){
                db.query_insert(sql, selectedDimensi, selectedDimensi2, jenis_hitungan, hasil, now,rs.getInt("id"));            
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(KalkulatorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kelilingpersegipanjangbuttonActionPerformed

    private void luaspersegipanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luaspersegipanjangActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int panjang = (Integer)panjangpersegipanjangspinner.getValue();
            int lebar = (Integer)lebarspinnerpersegipanjang.getValue();
            
            PersegiPanjang tb = new PersegiPanjang("none","none",panjang,lebar);
            double hasil = tb.luas();
            displaypersegipanjang.setText(String.valueOf(hasil));
            Database db = new Database();
            String selectedDimensi = (String) comboboxdimensi.getSelectedItem();
            String selectedDimensi2 = (String) jComboBoxgeometri.getSelectedItem();
            String jenis_hitungan = "LUas";
            LocalDateTime now = LocalDateTime.now();
            String sql = "insert into log_hitung (dimensi, jenis_bangun, jenis_hitungan, hasil, waktu, user_id) values (?, ?, ?, ?, ?, ?)";
            String sql2 = "Select * from data_user where username = ?";
            ResultSet rs = db.query_filter_login(sql2, this.usr);
            if(rs.next()){
                db.query_insert(sql, selectedDimensi, selectedDimensi2, jenis_hitungan, hasil, now,rs.getInt("id"));            
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(KalkulatorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_luaspersegipanjangActionPerformed

    private void kelilinglingkaranbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelilinglingkaranbuttonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int jari_jari = (Integer)jarijarilingkaranspinner.getValue();
            Lingkaran tb = new Lingkaran(jari_jari,"none","none");
            double hasil = tb.keliling();
            jTextField1.setText(String.valueOf(hasil));
            Database db = new Database();
            String selectedDimensi = (String) comboboxdimensi.getSelectedItem();
            String selectedDimensi2 = (String) jComboBoxgeometri.getSelectedItem();
            String jenis_hitungan = "Keliling";
            LocalDateTime now = LocalDateTime.now();
            String sql = "insert into log_hitung (dimensi, jenis_bangun, jenis_hitungan, hasil, waktu, user_id) values (?, ?, ?, ?, ?, ?)";
            String sql2 = "Select * from data_user where username = ?";
            ResultSet rs = db.query_filter_login(sql2, this.usr);
            if(rs.next()){
                db.query_insert(sql, selectedDimensi, selectedDimensi2, jenis_hitungan, hasil, now,rs.getInt("id"));            
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(KalkulatorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kelilinglingkaranbuttonActionPerformed

    private void luaslingkaranbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luaslingkaranbuttonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int jari_jari = (Integer)jarijarilingkaranspinner.getValue();
            Lingkaran tb = new Lingkaran(jari_jari,"none","none");
            double hasil = tb.luas();
            jTextField1.setText(String.valueOf(hasil));
            Database db = new Database();
            String selectedDimensi = (String) comboboxdimensi.getSelectedItem();
            String selectedDimensi2 = (String) jComboBoxgeometri.getSelectedItem();
            String jenis_hitungan = "Luas";
            LocalDateTime now = LocalDateTime.now();
            String sql = "insert into log_hitung (dimensi, jenis_bangun, jenis_hitungan, hasil, waktu, user_id) values (?, ?, ?, ?, ?, ?)";
            String sql2 = "Select * from data_user where username = ?";
            ResultSet rs = db.query_filter_login(sql2, this.usr);
            if(rs.next()){
                db.query_insert(sql, selectedDimensi, selectedDimensi2, jenis_hitungan, hasil, now,rs.getInt("id"));            
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(KalkulatorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_luaslingkaranbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorFrame("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Logtabel;
    private javax.swing.JSpinner alasprismaspinner;
    private javax.swing.JSpinner alassegitigaspinner;
    private javax.swing.JDialog balokdialog;
    private javax.swing.JButton buttonluaspermukaanbalok;
    private javax.swing.JComboBox<String> comboboxdimensi;
    private javax.swing.JTextField displaybalok;
    private javax.swing.JTextField displaykubus;
    private javax.swing.JTextField displaypersegipanjang;
    private javax.swing.JTextField displaytabung;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxgeometri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JSpinner jarijarilingkaranspinner;
    private javax.swing.JSpinner jarijarispinnertabung;
    private javax.swing.JButton kelilinglingkaranbutton;
    private javax.swing.JButton kelilingpersegibutton;
    private javax.swing.JButton kelilingpersegipanjangbutton;
    private javax.swing.JButton kelilingsegitigabutton;
    private javax.swing.JDialog kubusdialog;
    private javax.swing.JSpinner lebarspinnerbalok;
    private javax.swing.JSpinner lebarspinnerpersegipanjang;
    private javax.swing.JDialog lingkarandialog;
    private javax.swing.JButton luaslingkaranbutton;
    private javax.swing.JButton luaspermukaanprismabutton;
    private javax.swing.JButton luaspersegibutton;
    private javax.swing.JButton luaspersegipanjang;
    private javax.swing.JButton luassegitigabutton;
    private javax.swing.JSpinner panjangbalokspinner;
    private javax.swing.JSpinner panjangpersegipanjangspinner;
    private javax.swing.JDialog persegidialog;
    private javax.swing.JTextField persegidisplay;
    private javax.swing.JDialog persegipanjangdialog;
    private javax.swing.JButton pilihbutton;
    private javax.swing.JDialog prismadialog;
    private javax.swing.JTextField prismadisplay;
    private javax.swing.JButton refreshbutton;
    private javax.swing.JSpinner rusukkubusspinner;
    private javax.swing.JDialog segitigadialog;
    private javax.swing.JTextField segitigadisplay;
    private javax.swing.JSpinner sisi1prismaspinner;
    private javax.swing.JSpinner sisi1segitigaspinner;
    private javax.swing.JSpinner sisi2prismaspinner;
    private javax.swing.JSpinner sisi2segitigaspinner;
    private javax.swing.JSpinner sisispinner;
    private javax.swing.JDialog tabungdialog;
    private javax.swing.JSpinner tinggibalokspinner;
    private javax.swing.JSpinner tinggiprismaspinner;
    private javax.swing.JSpinner tinggisegitigaprismaspinner;
    private javax.swing.JSpinner tinggisegitigaspinner;
    private javax.swing.JSpinner tinggispinnertabung;
    private javax.swing.JButton volumebalokbutton;
    private javax.swing.JButton volumekubusbutton;
    private javax.swing.JButton volumeprismabutton;
    private javax.swing.JButton volumetabung;
    // End of variables declaration//GEN-END:variables
}
